<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>

	<table border="2px" width="100%" style="margin-bottom: 10px;">
		<tr>
			<td>PRODUCT</td>
			<td>CATEGORY</td>
			<td>CUSTOMER</td>
			<td>VENDOR</td>
			<td>SALESMAN</td>
			<td>SHIPPING METHOD</td>
			<td>PAYMENT METHOD</td>
		</tr>
	</table>

</body>
</html>