<?php 

$products = $this->getData();

?>


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>GRID</title>
</head>
<body>
	<table  width="100%" style="margin-bottom:10px";>
		<tr>
			<th> <h2>PRODUCT GRID</h2>	</th>
			<th> <button> <a href="index.php?c=Product&a=add">ADD</a> </button></th>
		</tr>
	</table>
	<table border="2px" width="100%" style="text-align: center;">
		<tr>
			<th>PRODUCT ID</th>
			<th>PRODUCT NAME</th>
			<th>COST</th>
			<th>PRICE</th>
			<th>SKU</th>
			<th>STATUS</th>
			<th>QUANTITY</th>
			<th>DISCRIPTION</th>
			<th>COLOR</th>
			<th>MATERIAL</th>
			<th>CREATED AT</th>
			<th>UPDATED AT</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php if (!$products): ?>
				<tr>
					<td colspan="14"> <h2>No Record Avilable.</h2></td>
				</tr>
		<?php  else: ?> 
			<?php foreach ($products as $product): ?>
				<tr>
					<td><?php echo $product->product_id; ?></td>
					<td><?php echo $product->product_name; ?></td>
					<td><?php echo $product->cost; ?></td>
					<td><?php echo $product->price; ?></td>
					<td><?php echo $product->sku; ?></td>
					<td><?php echo $product->status; ?></td>
					<td><?php echo $product->quantity; ?></td>
					<td><?php echo $product->discription; ?></td>
					<td><?php echo $product->color; ?></td>
					<td><?php echo $product->material; ?></td>
					<td><?php echo $product->created_at; ?></td>
					<td><?php echo $product->updated_at; ?></td>
					<td> <a href="index.php?c=Product&a=edit&id=<?php echo $product->product_id; ?>">EDIT</a> </td>
					<td> <a href="index.php?c=Product&a=delete&id=<?php echo $product->product_id; ?>">DELETE</a> </td>
				</tr>
			<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>