<?php 

// echo "<pre>";
// print_r($this);
// die();

?>


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>3 Columns</title>

</head>
<body>

		<table width="100%" border="1px solid bLack" style="text"  border-collapse: collapse;>
			<tr height="100">
				<td colspan="3"><?php $this->getChild('header')->render(); ?></td>
			</tr>
			<tr height="40">
				<td colspan="3"><?php $this->getChild('message')->render(); ?></td>
			</tr>
			<tr height="250">
				<td>Left</td>
				<td><?php $this->getChild('content')->render(); ?></td>
				<td>Right</td>
			</tr>
			<tr height="50">
				<td colspan="3"><?php $this->getChild('footer')->render(); ?></td>
			</tr>
		</table>

</body>
</html>

