<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>ADD</title>
</head>
<body>

	<?PHP require 'view/html/header.phtml'; ?>
	<table  width="100%" style="margin-bottom:10px;">
		<tr>
			<th> <h2>CUSTOMER ADD</h2>	</th>
		</tr>
	</table>

	<form action="index.php?c=Customer&a=save" method="POST">
		<table border="1px" style="text-align: center;margin-left: 550px">
			<tr>
				<td colspan="2">
					<h4>customer data</h4>
				</td>
			</tr>
			<tr>
				<td>FIRST NAME</td>
				<td> <input type="text" name="customer[first_name]"> </td>
			</tr>
			<tr>
				<td>LAST NAME</td>
				<td> <input type="text" name="customer[last_name]"> </td>
			</tr>
			<tr>
				<td>EMAIL</td>
				<td> <input type="text" name="customer[email]"> </td>
			</tr>
			<tr>
				<td>GENDER</td>
				<td> <input type="text" name="customer[gender]"> </td>
			</tr>
			<tr>
				<td>STATUS</td>
				<td>
					<select name="customer[status]">
						<option>SELECT BELOW</option>
						<option>ACTIVE</option>
						<option>INACTIVE</option>
					</select>

				</td>
			</tr>
			<tr>
				<td>MOBILE</td>
				<td> <input type="text" name="customer[mobile]"> </td>
			</tr>
		</table>

		<table border="1px" style="text-align: center;margin-left: 550px;margin-top: 10px;">
			<tr>
				<td colspan="2">
					<h4>billing address</h4>
				</td>
			</tr>
			<tr>
				<td>ADDRESS</td>
				<td> <input type="text" name="billing[address]"> </td>
			</tr>
			<tr>
				<td>CITY</td>
				<td> <input type="text" name="billing[city]"> </td>
			</tr>
			<tr>
				<td>STATE</td>
				<td> <input type="text" name="billing[state]"> </td>
			</tr>
			<tr>
				<td>COUNTRY</td>
				<td> <input type="text" name="billing[country]"> </td>
			</tr>
			<tr>
				<td>ZIPCODE</td>
				<td> <input type="text" name="billing[zipcode]"> </td>
			</tr>
		</table>

		<table border="1px" style="text-align: center;margin-left: 550px;margin-top: 10px;">
			<tr>
				<td colspan="2">
					<h4>shipping address</h4>
				</td>
			</tr>
			<tr>
				<td>ADDRESS</td>
				<td> <input type="text" name="shipping[address]"> </td>
			</tr>
			<tr>
				<td>CITY</td>
				<td> <input type="text" name="shipping[city]"> </td>
			</tr>
			<tr>
				<td>STATE</td>
				<td> <input type="text" name="shipping[state]"> </td>
			</tr>
			<tr>
				<td>COUNTRY</td>
				<td> <input type="text" name="shipping[country]"> </td>
			</tr>
			<tr>
				<td>ZIPCODE</td>
				<td> <input type="text" name="shipping[zipcode]"> </td>
			</tr>
			<tr>
				<th> <button> <a href="index.php?c=Customer&a=grid">CANCEL</a> </button></th>
				<th> <button type="submit"> SAVE </button></th>
			</tr>
		</table>
	</form>

</body>
</html>