<?php 


$customerData = $this->customerData;
$addressBilling = $this->addressBilling;
$addressShipping = $this->addressShipping;
// echo "<pre>";
// print_r($customerData);
// print_r($addressBilling);
// print_r($addressShipping);
// die();

?>

<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>EDIT</title>
</head>
<body>

	<?PHP require 'view/html/header.phtml'; ?>
	<table  width="100%" style="margin-bottom:10px";>
		<tr>
			<th> <h2>CUSTOMER EDIT</h2>	</th>
		</tr>
	</table>
	<form action="index.php?c=Customer&a=save&id=<?php echo $customerData->customer_id;; ?>" method="POST">
		<table border="1px" style="text-align: center; margin-left: 550px;">
			<tr>
				<td>FIRST NAME</td>
				<td> <input type="text" name="customer[first_name]" value="<?php echo $customerData->first_name; ?>">  </td>
			</tr>
			<tr>
				<td>LAST NAME</td>
				<td> <input type="text" name="customer[last_name]" value="<?php echo $customerData->last_name; ?>">  </td>
			</tr>
			<tr>
				<td>EMAIL</td>
				<td> <input type="text" name="customer[email]" value="<?php echo $customerData->email; ?>">  </td>
			</tr>
			<tr>
				<td>GENDER</td>
				<td> <input type="text" name="customer[gender]" value="<?php echo $customerData->gender; ?>">  </td>
			</tr>
			<tr>
				<td>STATUS</td>
				<td>
					<select name="customer[status]" value="<?php echo $customerData->status; ?>"> 
						<option>SELECT BELOW</option>
						<option>ACTIVE</option>
						<option>INACTIVE</option>
					</select>

				</td>
			</tr>
			<tr>
				<td>MOBILE</td>
				<td> <input type="text" name="customer[mobile]" value="<?php echo $customerData->mobile; ?>">  </td>
			</tr>
		</table>

		<table border="1px" style="text-align: center;margin-left: 550px;margin-top: 10px;">
			<tr>
				<td colspan="2">
					<h4>billing address</h4>
				</td>
			</tr>
			<tr>
				<td>ADDRESS</td>
				<td> <input type="text" name="billing[address]" value="<?php echo $addressBilling->address; ?>"> </td>
			</tr>
			<tr>
				<td>CITY</td>
				<td> <input type="text" name="billing[city]" value="<?php echo $addressBilling->city; ?>"> </td>
			</tr>
			<tr>
				<td>STATE</td>
				<td> <input type="text" name="billing[state]" value="<?php echo $addressBilling->state; ?>"> </td>
			</tr>
			<tr>
				<td>COUNTRY</td>
				<td> <input type="text" name="billing[country]" value="<?php echo $addressBilling->country; ?>"> </td>
			</tr>
			<tr>
				<td>ZIPCODE</td>
				<td> <input type="text" name="billing[zipcode]" value="<?php echo $addressBilling->zipcode; ?>"> </td>
			</tr>
		</table>

		<table border="1px" style="text-align: center;margin-left: 550px;margin-top: 10px;">
			<tr>
				<td colspan="2">
					<h4>shipping address</h4>
				</td>
			</tr>
			<tr>
				<td>ADDRESS</td>
				<td> <input type="text" name="shipping[address]" value="<?php echo $addressShipping->address; ?>"> </td>
			</tr>
			<tr>
				<td>CITY</td>
				<td> <input type="text" name="shipping[city]" value="<?php echo $addressShipping->city; ?>"> </td>
			</tr>
			<tr>
				<td>STATE</td>
				<td> <input type="text" name="shipping[state]" value="<?php echo $addressShipping->state; ?>"> </td>
			</tr>
			<tr>
				<td>COUNTRY</td>
				<td> <input type="text" name="shipping[country]" value="<?php echo $addressShipping->country; ?>"> </td>
			</tr>
			<tr>
				<td>ZIPCODE</td>
				<td> <input type="text" name="shipping[zipcode]" value="<?php echo $addressShipping->zipcode; ?>"> </td>
			</tr>
			<tr>
				<th> <button> <a href="index.php?c=Customer&a=grid">CANCEL</a> </button></th>
				<th> <button type="submit"> SAVE </button></th>
			</tr>
		</table>
	</form>

</body>
</html>