<?php 

$categories = $this->categories;

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>GRID</title>
</head>
<body>
	<?PHP require 'view/html/header.phtml'; ?>
	<table  width="100%" style="margin-bottom:10px";>
		<tr>
			<th> <h2>CATEGORY GRID</h2>	</th>
			<th> <button> <a href="index.php?c=Category&a=add">ADD</a> </button></th>
		</tr>
	</table>
	<table border="2px" width="100%" style="text-align: center;border-collapse: collapse;">
		<tr>
			<th>CATEGORY ID</th>
			<th>PARENT ID</th>
			<th>CATEGORY NAME</th>
			<th>PATH</th>
			<th>STATUS</th>
			<th>DISCRIPTION</th>
			<th>CREATED AT</th>
			<th>UPDATED AT</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php if (!$categories): ?>
				<tr>
					<td colspan="14"> <h2>No Record Avilable.</h2></td>
				</tr>
		<?php  else: ?> 
			<?php foreach ($categories as $category): ?>
				<tr>
					<td><?php echo $category->category_id; ?></td>
					<td><?php echo $category->parent_id; ?></td>
					<td><?php echo $category->getPathName($category->path); ?></td>
					<td><?php echo $category->path; ?></td>
					<td><?php echo $category->status; ?></td>
					<td><?php echo $category->discription; ?></td>
					<td><?php echo $category->created_at; ?></td>
					<td><?php echo $category->updated_at; ?></td>
					<td> <a href="index.php?c=Category&a=edit&id=<?php echo $category->category_id; ?>">EDIT</a> </td>
					<td> <a href="index.php?c=Category&a=delete&id=<?php echo $category->category_id; ?>">DELETE</a> </td>
				</tr>
			<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>